### ISSUE TITLE
After dragging a letter to the board and refreshing the page, there will sometimes be a tile with no letter

### ISSUE THREAD

**Issue by atuley** [zkayser/elm_scrabble#3]
Sometimes after dragging a letter to the board and refreshing the page, there will be a blank letter tile. I'm not sure if this is intended or not but I just wanted to point it out.

**Comment by zkayser** [comment]
Those are actually intended. Real Scrabble has two blank tiles that can stand in as wild-cards characters, so there is a 2/100 chance that they pop up. I had to read the [rules](https://scrabble.hasbro.com/en-us/rules). I didn't know that was a thing either.
